### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by anhdt-vnpay**

### CODE REVIEW

**Comment by anhdt-vnpay** [comment]
@CodiumAI-Agent /describe
--pr_description.extra_instructions="
For the title, use the format [type]: [summary]
"
--pr_description.publish_labels=true
--pr_description.publish_description_as_comment=true
--pr_description.generate_ai_title=true
--pr_description.final_update_message=true

**Comment by anhdt-vnpay** [comment]
@CodiumAI-Agent /review
--pr_reviewer.inline_code_comments=true
--pr_reviewer.require_score_review=true
--pr_reviewer.num_code_suggestions="0"

**Comment by anhdt-vnpay** [comment]
@CodiumAI-Agent /review
--pr_reviewer.inline_code_comments=true
--pr_reviewer.require_score_review=true
--pr_reviewer.require_can_be_split_review=true
--pr_reviewer.num_code_suggestions="8"

**Comment by anhdt-vnpay** [comment]
@CodiumAI-Agent /improve

**Comment by anhdt-vnpay** [comment]
This pull request introduces several significant changes across various files to enhance the configuration, command handling, and synchronization processes. The main changes include the addition of configuration settings, new command implementations, and the integration of synchronization and task processing services.

### Configuration Enhancements:
* [`appconfig/config.go`](diffhunk://#diff-47f45d9c2c59b539182ebe6ba86af2b8880f40ab46d6b4858581c0ea024cc742R2-R222): Introduced new configuration settings and initialization functions to handle application configurations, including database and ledger settings.
* [`config/config.yaml`](diffhunk://#diff-38df760413887d0cc4ee5707919e6390456a863d326f6080644cc3d9c72e4bbaR1-R41): Added detailed configuration parameters for ledger, storage, and database settings.
* [`config/fabric-config-test.json`](diffhunk://#diff-e982be637bc00f8eed0398d05546632f117ad9cdf200a64e856e6f0c6948a3c2R1-R46): Added a new JSON configuration file for Fabric network settings.

### Command Implementations:
* [`cmd/cmd.go`](diffhunk://#diff-8e494a434a8037b6c0b888e25b2baae7618fe65e792d4a155dadd096e9350667R20-R59): Added new commands (`versionCmd`, `syncCmd`, and `processTasksCmd`) for version printing, block synchronization, and task processing.
* [`cmd/sync.go`](diffhunk://#diff-6f5f9ca9ac82cbfb03857438b7f2b2373c6ddf3db19f1f68e7074242baebaadcR1-R48): Implemented the synchronization command to handle block synchronization from the blockchain.
* [`cmd/tasks.go`](diffhunk://#diff-1b5d75686c7c5f1907c7542be728036ec235e8082046ba12206d38e63945402aR1-R45): Implemented the task processing command to manage task execution and monitoring.

### Documentation:
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R2-R9): Updated the README with instructions for configuring private Git packages.

### Miscellaneous:
* [`.doc/task-flow.drawio`](diffhunk://#diff-44bd4a1dfc5ebe26954061551aaf8a86f5a8427286544c2b3e3e8c5b9a6cd624R1-R124): Added a new diagram to illustrate the task flow within the system.
* [`common/common.go`](diffhunk://#diff-a70f47b70b2d542f3eaa01a097d0f6d97e1f49cee567e258d4afc2a79f07af92R2-R7): Added new date format constants for common usage.

These changes collectively improve the application's configuration management, command execution capabilities, and documentation.

**Comment by tuananh-vn** [comment]
This pull request introduces several significant changes to the project, including the addition of new configuration files, updates to the command-line interface, and the implementation of new services for task processing and synchronization. Below are the most important changes grouped by theme:

### Configuration Management:
* Added a new configuration file `config/config.yaml` with settings for Ledger, Storage, and DB. This includes parameters such as `MaxQueryGoroutine`, `BlockMainQueueSize`, and database connection details.
* Introduced a new JSON configuration file `config/fabric-config-test.json` for fabric network settings, including peer and orderer configurations.
* Implemented the `appconfig/config.go` file to handle loading and parsing of configuration settings, including database and ledger configurations.

### Command-Line Interface Enhancements:
* Enhanced the CLI in `cmd/cmd.go` by adding new commands: `version`, `sync`, and `process-task`, each with specific functionalities and flags.
* Created a new `cmd/sync.go` file to define the `sync` command, which initializes configuration, sets up the ledger repository, and starts the sync service.
* Added `cmd/tasks.go` to define the `process-task` command, which initializes configuration, sets up task repositories, and starts the task processing service.

### Documentation:
* Updated `README.md` with instructions on configuring Git for private packages and running `go mod vendor`.

### Miscellaneous:
* Added a new constants block in `common/common.go` for date formats.
* Included a new task flow diagram in `.doc/task-flow.drawio` to visually represent the task processing flow.

**Comment by tuananh-vn** [comment]
@CodiumAI-Agent /review
--pr_reviewer.inline_code_comments=true
-i
--pr_reviewer.require_score_review=true
--pr_reviewer.num_code_suggestions="0"

**Comment by anhdt-vnpay** [comment]
Preparing review...

**Comment by anhdt-vnpay** [comment]
Preparing review...

**Pull request closed without merging**
